import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#203033',
        'primary-container': '#0F3C49',
        'on-primary': '#ffffff',
        'on-primary-container': '#7ea6b6',
        secondary: '#318491',
        'secondary-container': '#9eecfd',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#0b6c7b',
        tertiary: '#0a2528',
        'tertiary-container': '#223b3e',
        'on-tertiary-container': '#8aa5a8',
        'tertiary-fixed': '#cce8eb',
        'tertiary-fixed-dim': '#b0ccce',
        surface: '#F7FAFB',
        'surface-dim': '#D7DADC',
        'surface-bright': '#F7FAFB',
        'surface-variant': '#E0E3E4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#F1F4F5',
        'surface-container': '#EBEEEF',
        'surface-container-high': '#E5E9EA',
        'surface-container-highest': '#E0E3E4',
        'on-surface': '#181C1D',
        'on-surface-variant': '#41484b',
        outline: '#71787b',
        'outline-variant': '#C1C7CB',
        background: '#F7FAFB',
        'on-background': '#181C1D',
        error: '#BA1A1A',
        'error-container': '#ffdad6',
        'inverse-surface': '#2E3133',
        'inverse-on-surface': '#EEF1F2',
        'inverse-primary': '#a4cddd',
        'primary-fixed': '#bfe9fa',
        'primary-fixed-dim': '#a4cddd',
        'secondary-fixed': '#a3eeff',
        'secondary-fixed-dim': '#85d2e3',
        'on-primary-fixed': '#001f28',
        'on-secondary-fixed': '#001f25',
        'mint-accent': '#e0f2f1',
      },
      fontFamily: {
        headline: ['Noto Serif', 'Georgia', 'serif'],
        body: ['Manrope', 'Inter', 'system-ui', 'sans-serif'],
        label: ['Manrope', 'Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
      maxWidth: {
        site: '1440px',
      },
      boxShadow: {
        'editorial': '0 20px 60px -15px rgba(15, 60, 73, 0.05)',
        'editorial-hover': '0 30px 80px -15px rgba(15, 60, 73, 0.10)',
        'soft': '0 4px 30px rgba(0, 0, 0, 0.04)',
        'card-hover': '0 20px 40px -15px rgba(0, 38, 48, 0.08)',
      },
    },
  },
  plugins: [],
};

export default config;
